#!/usr/bin/env python3
"""Validate docs/HANDOFF.md and render a deterministic local HTML report."""

from __future__ import annotations

import argparse
import base64
from datetime import datetime
import hashlib
import html
import os
from pathlib import Path, PurePosixPath
import re
import stat
import sys
import tempfile
from typing import Any
import uuid


MARKER_PREFIX = "<!-- Generated by Handoff renderer;"
MAX_FILE_BYTES = 1_048_576
MAX_OUTPUT_BYTES = 8_388_608
REQUIRED_METADATA = {
    "Format",
    "Receipt",
    "Work status",
    "Project scope",
    "Last verified",
    "Baseline commit",
    "Branch or worktree",
    "First action",
}
REQUIRED_SECTIONS = [
    "Resume instructions",
    "Strategic alignment",
    "Documentation alignment",
    "Global success criteria",
    "Plan review",
    "Execution plan",
    "Evidence",
    "State verification",
    "Risks and open questions",
    "Required context",
    "New-session prompt",
]
RECEIPT_STATUSES = {"READY", "STALE", "INVALID"}
WORK_STATUSES = {"ACTIVE", "BLOCKED", "COMPLETE"}
SUPPORTED_FORMATS = {
    "handoff-v2",
    "handoff-v3",
    "handoff-v4",
    "handoff-v5",
    "handoff-v6",
    "handoff-v7",
    "handoff-v8",
}
CRITERION_STATUSES = {"PASS", "FAIL", "UNVERIFIED"}
ALIGNMENT_STATUSES = {
    "ALIGNED",
    "CONFLICT",
    "UNVERIFIED",
    "NOT_APPLICABLE",
}
STAGE_STATES = {"PENDING", "ACTIVE", "BLOCKED", "PASS"}
COMMON_GATES = {
    "deliverable",
    "scope",
    "documentation",
    "verification",
    "evidence",
    "next-input",
}
TABLE_SCHEMAS = {
    "Documentation alignment": [
        "Topic or decision",
        "Authority",
        "Alignment",
        "Action",
        "Evidence",
    ],
    "Global success criteria": [
        "ID",
        "Criterion",
        "Required",
        "Status",
        "Evidence",
    ],
    "Plan review": [
        "Change",
        "Previous",
        "Revised",
        "Reason",
        "Documentation impact",
    ],
    "Evidence": ["ID", "Kind", "Result", "Summary", "Reference"],
}
STAGE_TABLE_SCHEMA = ["Gate or criterion", "Status", "Evidence"]
METADATA_PATTERN = re.compile(r"^([^:\n]+):\s*(.+)$")
STAGE_HEADING_PATTERN = re.compile(r"^(S[1-9][0-9]*)\s+—\s+(.+)$")
EVIDENCE_ID_PATTERN = re.compile(r"\bE[1-9][0-9]*\b")
ROUTING_HEADING = "### Next-stage routing"
CONTINUATION_HEADING = "### Continuation decision"
CHECKLIST_HEADING = "### Handoff completion checklist"
WORK_SUMMARY_HEADING = "### 작업 결과 요약"
WORK_SUMMARY_FIELDS = (
    "한 줄 결과",
    "바뀐 점",
    "이제 가능한 것",
    "확인한 내용",
    "남은 사항",
)
CONTINUATION_FIELDS = ("Mode", "Branch or worktree", "Instruction")
CONTINUATION_MODES = {"PAUSE", "PREPARE_PR_FIRST", "CONTINUE_CURRENT_WORKTREE"}
UNFINISHED_CHECKLIST_FIELDS = (
    "repository-snapshot",
    "work-state",
    "documentation",
    "evidence",
    "resume-ready",
)
COMPLETE_CHECKLIST_FIELDS = (
    "repository-snapshot",
    "work-state",
    "documentation",
    "evidence",
    "completion",
)
LEGACY_ROUTING_FIELDS = (
    "Goal",
    "Completion condition",
    "Current stage",
    "Change scope",
    "Recommended model",
    "Recommended reasoning",
    "Use Ultra",
    "Escalate to Sol High when",
    "Next checkpoint",
)
V6_ROUTING_FIELDS = (
    "Goal",
    "Completion condition",
    "Current stage",
    "Change scope",
    "Recommended model",
    "Recommended reasoning",
    "Route availability",
    "Fallback model",
    "Fallback reasoning",
    "Use Ultra",
    "Escalate to Sol High when",
    "Next checkpoint",
)
# Kept as the legacy schema alias for callers that inspect pre-v6 receipts.
ROUTING_FIELDS = LEGACY_ROUTING_FIELDS
LEGACY_ROUTING_COMBINATIONS = {
    ("Terra", "Medium"),
    ("Terra", "High"),
    ("Sol", "Medium"),
    ("Sol", "High"),
    ("Sol", "Extra High"),
}
V6_ROUTING_COMBINATIONS = {
    ("Luna", "Medium"),
    ("Luna", "High"),
    ("Luna", "Extra High"),
    ("Terra", "Medium"),
    ("Terra", "High"),
    ("Terra", "Extra High"),
    ("Sol", "Light"),
    ("Sol", "Medium"),
    ("Sol", "High"),
    ("Sol", "Extra High"),
    ("Astra", "Medium"),
    ("Astra", "High"),
}
# Public name for the routing policy used by newly prepared receipts.
V7_ROUTING_COMBINATIONS = V6_ROUTING_COMBINATIONS - {
    ("Luna", "Extra High"), ("Sol", "High"), ("Sol", "Extra High"),
}
V7_ROUTING_FIELDS = tuple(
    "Escalate when" if field == "Escalate to Sol High when" else field
    for field in LEGACY_ROUTING_FIELDS
)
ROUTING_COMBINATIONS = V7_ROUTING_COMBINATIONS
LEGACY_BELOW_MINIMUM_COMBINATIONS = {
    ("Luna", "Light"),
    ("Terra", "Light"),
}
TOP_ROUTE_ESCALATION_PREFIX = "Already at Sol + Extra High;"
TOP_ROUTE_EVIDENCE_PREFIX = "Top-route evidence:"
DELIVERY_ACTION_PATTERN = re.compile(
    r"\b(?:commit|push|pull request|pr|merge|create (?:a )?(?:new )?branch|"
    r"open (?:a )?pr)\b|커밋|푸시|풀 리퀘스트|병합|"
    r"(?<![가-힣])머지(?:(?:를|가|는|도|만|로)(?![가-힣])|"
    r"(?:하|한|합|해|했|할|되|된|됩|돼|됐|될)[가-힣]*|"
    r"(?=[^가-힣]|$))|브랜치 생성",
    re.IGNORECASE,
)
ROUTING_ADVISORY = "Routing is advisory: revalidate repository state and adjust model, reasoning, or Ultra if evidence changed."
CURRENT_PROMPT_COMMAND = "$handoff start"
NO_COPYABLE_PROMPT = "No copyable prompt: start reads this receipt directly."
PROMPT_STAGE_FIELDS = LEGACY_ROUTING_FIELDS[:4]
PROMPT_SETUP_FIELDS = LEGACY_ROUTING_FIELDS[4:]


class HandoffError(ValueError):
    pass


def fail(message: str) -> None:
    raise HandoffError(message)


def require_development_work(value: str, subject: str) -> None:
    if DELIVERY_ACTION_PATTERN.search(value):
        fail(f"{subject} must name development work, not a delivery action")


def parse_work_summary(lines: list[str]) -> dict[str, str] | None:
    heading_indexes = [
        index
        for index, line in enumerate(lines)
        if line.strip() == WORK_SUMMARY_HEADING
    ]
    if len(heading_indexes) > 1:
        fail("Resume instructions has duplicate 작업 결과 요약 headings")
    if not heading_indexes:
        return None
    values: dict[str, str] = {}
    order: list[str] = []
    for line in lines[heading_indexes[0] + 1 :]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("### "):
            fail("작업 결과 요약 must be the final Resume instructions subsection")
        match = re.fullmatch(r"-\s+([^:\n]+):\s*(.+)", stripped)
        if match is None:
            fail("작업 결과 요약 must contain only '- 항목: 내용' lines")
        key = match.group(1).strip()
        if key in values:
            fail(f"duplicate 작업 결과 요약 field: {key}")
        if key not in WORK_SUMMARY_FIELDS:
            fail(f"unknown 작업 결과 요약 field: {key}")
        values[key] = nonempty(match.group(2), f"작업 결과 요약.{key}")
        order.append(key)
    if tuple(order) != WORK_SUMMARY_FIELDS:
        fail("작업 결과 요약 fields must appear in the required order")
    return values


def is_link_path(path: Path) -> bool:
    if path.is_symlink():
        return True
    if os.name == "nt" and path.exists():
        attributes = getattr(os.lstat(path), "st_file_attributes", 0)
        reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
        if attributes & reparse_flag:
            return True
    junction_check = getattr(path, "is_junction", None)
    return bool(junction_check and junction_check())


def reject_link_components(root: Path, target: Path) -> None:
    try:
        relative = target.relative_to(root)
    except ValueError:
        fail(f"path escapes project root: {target}")
    current = root
    if is_link_path(current):
        fail(f"project root must not be a link or junction: {root}")
    for part in relative.parts:
        current = current / part
        if current.exists() and is_link_path(current):
            fail(f"managed path contains a link or junction: {current}")


def resolve_inside(root: Path, raw: str, *, must_exist: bool) -> Path:
    candidate = Path(raw)
    if not candidate.is_absolute():
        candidate = root / candidate
    lexical = Path(os.path.abspath(candidate))
    try:
        lexical.relative_to(root)
    except ValueError:
        fail(f"path escapes project root: {raw}")
    reject_link_components(root, lexical)
    resolved = lexical.resolve(strict=must_exist)
    try:
        resolved.relative_to(root)
    except ValueError:
        fail(f"path escapes project root: {raw}")
    return resolved


def read_regular_utf8(path: Path) -> bytes:
    with path.open("rb") as handle:
        before = os.fstat(handle.fileno())
        if not stat.S_ISREG(before.st_mode):
            fail(f"input must be a regular file: {path}")
        if before.st_size > MAX_FILE_BYTES:
            fail(f"input is too large: {path}")
        raw = handle.read(MAX_FILE_BYTES + 1)
        after = os.fstat(handle.fileno())
    if len(raw) > MAX_FILE_BYTES:
        fail(f"input is too large: {path}")
    identity_before = (
        before.st_dev,
        before.st_ino,
        before.st_size,
        before.st_mtime_ns,
    )
    identity_after = (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
    )
    if identity_before != identity_after:
        fail(f"input changed while being read: {path}")
    if b"\x00" in raw:
        fail(f"input contains a null byte: {path}")
    try:
        raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        fail(f"input must be UTF-8: {exc}")
    return raw


def nonempty(value: str, path: str) -> str:
    result = value.strip()
    if not result:
        fail(f"{path} must not be empty")
    return result


def split_pipe_row(line: str) -> list[str]:
    stripped = line.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    cells: list[str] = []
    current: list[str] = []
    escaped = False
    for character in stripped:
        if escaped:
            if character != "|":
                current.append("\\")
            current.append(character)
            escaped = False
        elif character == "\\":
            escaped = True
        elif character == "|":
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(character)
    if escaped:
        current.append("\\")
    cells.append("".join(current).strip())
    return cells


def is_table_separator(cells: list[str]) -> bool:
    return bool(cells) and all(
        re.fullmatch(r":?-{3,}:?", cell.replace(" ", "")) is not None
        for cell in cells
    )


def parse_table(lines: list[str], section: str) -> dict[str, Any]:
    table_lines = [line for line in lines if line.strip().startswith("|")]
    if len(table_lines) < 2:
        fail(f"{section} must contain a Markdown table")
    header = split_pipe_row(table_lines[0])
    separator = split_pipe_row(table_lines[1])
    if len(separator) != len(header) or not is_table_separator(separator):
        fail(f"{section} has an invalid table separator")
    expected = TABLE_SCHEMAS.get(section, STAGE_TABLE_SCHEMA)
    if header != expected:
        fail(
            f"{section} table columns must be exactly: "
            + " | ".join(expected)
        )
    rows: list[dict[str, str]] = []
    for index, line in enumerate(table_lines[2:], start=1):
        cells = split_pipe_row(line)
        if len(cells) != len(header):
            fail(f"{section} row {index} has the wrong number of cells")
        row = {name: nonempty(value, f"{section} row {index}.{name}") for name, value in zip(header, cells)}
        rows.append(row)
    if not rows:
        fail(f"{section} table must contain at least one data row")
    return {"headers": header, "rows": rows}


def parse_metadata(lines: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        match = METADATA_PATTERN.fullmatch(stripped)
        if match is None:
            fail(f"invalid metadata line: {stripped}")
        key = match.group(1).strip()
        if key in values:
            fail(f"duplicate metadata field: {key}")
        values[key] = nonempty(match.group(2), key)
    missing = REQUIRED_METADATA - values.keys()
    extra = values.keys() - REQUIRED_METADATA
    if missing:
        fail("missing metadata fields: " + ", ".join(sorted(missing)))
    if extra:
        fail("unknown metadata fields: " + ", ".join(sorted(extra)))
    if values["Format"] not in SUPPORTED_FORMATS:
        fail(
            "Format must be handoff-v2, handoff-v3, handoff-v4, "
            "handoff-v5, handoff-v6, handoff-v7, or handoff-v8"
        )
    if values["Receipt"] not in RECEIPT_STATUSES:
        fail("Receipt has an unsupported value")
    if values["Work status"] not in WORK_STATUSES:
        fail("Work status has an unsupported value")
    raw_scope = values["Project scope"]
    project_scope = PurePosixPath(raw_scope)
    if (
        "\\" in raw_scope
        or project_scope.is_absolute()
        or ".." in project_scope.parts
        or raw_scope not in {".", project_scope.as_posix()}
    ):
        fail("Project scope must be . or a safe Git-relative POSIX path")
    timestamp = values["Last verified"].replace("Z", "+00:00")
    try:
        verified_at = datetime.fromisoformat(timestamp)
    except ValueError:
        fail("Last verified must be an ISO 8601 timestamp with timezone")
    if verified_at.tzinfo is None or verified_at.utcoffset() is None:
        fail("Last verified must include a timezone")
    return values


def split_sections(lines: list[str]) -> tuple[list[str], dict[str, list[str]]]:
    metadata_lines: list[str] = []
    sections: dict[str, list[str]] = {}
    current: str | None = None
    in_fence = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            if current is None:
                fail("metadata must not contain fenced code")
            sections[current].append(line)
            in_fence = not in_fence
            continue
        if not in_fence and line.startswith("## "):
            name = line[3:].strip()
            if name in sections:
                fail(f"duplicate section: {name}")
            sections[name] = []
            current = name
            continue
        if current is None:
            metadata_lines.append(line)
        else:
            sections[current].append(line)
    if in_fence:
        fail("document contains an unclosed fenced code block")
    missing = [name for name in REQUIRED_SECTIONS if name not in sections]
    extra = [name for name in sections if name not in REQUIRED_SECTIONS]
    if missing:
        fail("missing sections: " + ", ".join(missing))
    if extra:
        fail("unknown sections: " + ", ".join(extra))
    if list(sections) != REQUIRED_SECTIONS:
        fail("sections must appear in the required order")
    for name, section_lines in sections.items():
        if not any(line.strip() for line in section_lines):
            fail(f"{name} must not be empty")
    return metadata_lines, sections


def parse_stage_metadata(lines: list[str], stage_id: str) -> dict[str, str]:
    required = {
        "State",
        "Maps to",
        "Outcome",
        "Scope",
        "Verification",
        "First action",
    }
    values: dict[str, str] = {}
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("|"):
            continue
        match = METADATA_PATTERN.fullmatch(stripped)
        if match is None:
            fail(f"{stage_id} has invalid metadata: {stripped}")
        key = match.group(1).strip()
        if key in values:
            fail(f"{stage_id} has duplicate metadata: {key}")
        values[key] = nonempty(match.group(2), f"{stage_id}.{key}")
    missing = required - values.keys()
    extra = values.keys() - required
    if missing:
        fail(f"{stage_id} is missing: " + ", ".join(sorted(missing)))
    if extra:
        fail(f"{stage_id} has unknown metadata: " + ", ".join(sorted(extra)))
    if values["State"] not in STAGE_STATES:
        fail(f"{stage_id}.State has an unsupported value")
    return values


def parse_stages(lines: list[str]) -> list[dict[str, Any]]:
    content = [line.strip() for line in lines if line.strip()]
    if content == ["No remaining stages."]:
        return []

    stages: list[dict[str, Any]] = []
    current_heading: str | None = None
    current_lines: list[str] = []
    preface: list[str] = []
    in_fence = False

    def append_current() -> None:
        if current_heading is None:
            return
        match = STAGE_HEADING_PATTERN.fullmatch(current_heading)
        if match is None:
            fail(f"invalid stage heading: {current_heading}")
        stage_id = match.group(1)
        if any(stage["id"] == stage_id for stage in stages):
            fail(f"duplicate stage id: {stage_id}")
        metadata = parse_stage_metadata(current_lines, stage_id)
        table = parse_table(current_lines, stage_id)
        stages.append(
            {
                "id": stage_id,
                "name": nonempty(match.group(2), f"{stage_id}.name"),
                "metadata": metadata,
                "table": table,
            }
        )

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            in_fence = not in_fence
        if not in_fence and line.startswith("### "):
            append_current()
            current_heading = line[4:].strip()
            current_lines = []
        elif current_heading is None:
            if line.strip():
                preface.append(line)
        else:
            current_lines.append(line)
    if in_fence:
        fail("Execution plan contains an unclosed fenced code block")
    append_current()
    if preface:
        fail("Execution plan must contain only stage subsections")
    if not stages:
        fail(
            "Execution plan must contain a stage or exactly "
            "'No remaining stages.'"
        )
    return stages



def parse_routing(lines: list[str], format_name: str) -> dict[str, str] | None:
    heading_indexes = [
        index
        for index, line in enumerate(lines)
        if line.strip() == ROUTING_HEADING
    ]
    if len(heading_indexes) > 1:
        fail("Required context has duplicate Next-stage routing headings")
    if not heading_indexes:
        return None

    routing_fields = (
        V7_ROUTING_FIELDS
        if format_name in {"handoff-v7", "handoff-v8"}
        else V6_ROUTING_FIELDS
        if format_name == "handoff-v6"
        else LEGACY_ROUTING_FIELDS
    )
    values: dict[str, str] = {}
    order: list[str] = []
    start = heading_indexes[0] + 1
    for line in lines[start:]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("### "):
            fail("Next-stage routing must be the final Required context subsection")
        match = re.fullmatch(r"-\s+([^:\n]+):\s*(.+)", stripped)
        if match is None:
            fail("Next-stage routing must contain only '- Key: value' lines")
        key = match.group(1).strip()
        if key in values:
            fail(f"duplicate next-stage routing field: {key}")
        if key not in routing_fields:
            fail(f"unknown next-stage routing field: {key}")
        values[key] = nonempty(match.group(2), f"Next-stage routing.{key}")
        order.append(key)

    missing = [key for key in routing_fields if key not in values]
    if missing:
        fail("missing next-stage routing fields: " + ", ".join(missing))
    if tuple(order) != routing_fields:
        fail("next-stage routing fields must appear in the required order")
    return values
def parse_continuation(lines: list[str]) -> dict[str, str] | None:
    heading_indexes = [
        index
        for index, line in enumerate(lines)
        if line.strip() == CONTINUATION_HEADING
    ]
    if len(heading_indexes) > 1:
        fail("Required context has duplicate Continuation decision headings")
    if not heading_indexes:
        return None
    start = heading_indexes[0] + 1
    end = next(
        (
            index
            for index in range(start, len(lines))
            if lines[index].strip().startswith("### ")
        ),
        len(lines),
    )
    values: dict[str, str] = {}
    order: list[str] = []
    for line in lines[start:end]:
        stripped = line.strip()
        if not stripped:
            continue
        match = re.fullmatch(r"-\s+([^:\n]+):\s*(.+)", stripped)
        if match is None:
            fail("Continuation decision must contain only '- Key: value' lines")
        key = match.group(1).strip()
        if key in values:
            fail(f"duplicate continuation decision field: {key}")
        if key not in CONTINUATION_FIELDS:
            fail(f"unknown continuation decision field: {key}")
        values[key] = nonempty(match.group(2), f"Continuation decision.{key}")
        order.append(key)
    if tuple(order) != CONTINUATION_FIELDS:
        fail("Continuation decision fields must appear in the required order")
    return values


def parse_completion_checklist(lines: list[str]) -> dict[str, dict[str, str]] | None:
    heading_indexes = [
        index
        for index, line in enumerate(lines)
        if line.strip() == CHECKLIST_HEADING
    ]
    if len(heading_indexes) > 1:
        fail("State verification has duplicate Handoff completion checklist headings")
    if not heading_indexes:
        return None
    start = heading_indexes[0] + 1
    values: dict[str, dict[str, str]] = {}
    for line in lines[start:]:
        stripped = line.strip()
        if not stripped:
            continue
        match = re.fullmatch(r"-\s+([a-z-]+):\s+(PASS|FAIL|UNVERIFIED);\s*(.+)", stripped)
        if match is None:
            fail("Handoff completion checklist must contain only '- check: STATUS; evidence' lines")
        key, status, evidence = match.groups()
        if key in values:
            fail(f"duplicate handoff completion checklist item: {key}")
        values[key] = {"Status": status, "Evidence": nonempty(evidence, key)}
    if not values:
        fail("Handoff completion checklist must contain at least one item")
    return values

def evidence_ids(value: str) -> set[str]:
    return set(EVIDENCE_ID_PATTERN.findall(value))


def validate_model(model: dict[str, Any]) -> None:
    metadata = model["metadata"]
    tables = model["tables"]
    stages = model["stages"]

    evidence_rows = tables["Evidence"]["rows"]
    evidence_index: dict[str, dict[str, str]] = {}
    for row in evidence_rows:
        item_id = row["ID"]
        if re.fullmatch(r"E[1-9][0-9]*", item_id) is None:
            fail(f"invalid evidence id: {item_id}")
        if item_id in evidence_index:
            fail(f"duplicate evidence id: {item_id}")
        if row["Result"] not in CRITERION_STATUSES:
            fail(f"{item_id}.Result must be PASS, FAIL, or UNVERIFIED")
        evidence_index[item_id] = row

    def require_pass_evidence(refs: set[str], subject: str) -> None:
        non_passing = sorted(
            item_id
            for item_id in refs
            if evidence_index[item_id]["Result"] != "PASS"
        )
        if non_passing:
            fail(f"{subject} PASS references non-PASS evidence: {non_passing}")

    criterion_rows = tables["Global success criteria"]["rows"]
    criterion_index: dict[str, dict[str, str]] = {}
    for row in criterion_rows:
        item_id = row["ID"]
        if re.fullmatch(r"C[1-9][0-9]*", item_id) is None:
            fail(f"invalid global criterion id: {item_id}")
        if item_id in criterion_index:
            fail(f"duplicate global criterion id: {item_id}")
        if row["Required"].lower() not in {"yes", "no"}:
            fail(f"{item_id}.Required must be yes or no")
        if row["Status"] not in CRITERION_STATUSES:
            fail(f"{item_id}.Status has an unsupported value")
        refs = evidence_ids(row["Evidence"])
        if row["Status"] == "PASS" and not refs:
            fail(f"{item_id} PASS requires an evidence ID")
        unknown_refs = refs - evidence_index.keys()
        if unknown_refs:
            fail(f"{item_id} references unknown evidence: {sorted(unknown_refs)}")
        if row["Status"] == "PASS":
            require_pass_evidence(refs, item_id)
        criterion_index[item_id] = row

    unresolved_documentation = False
    for index, row in enumerate(tables["Documentation alignment"]["rows"], start=1):
        status = row["Alignment"]
        if status not in ALIGNMENT_STATUSES:
            fail(f"Documentation alignment row {index} has an unsupported status")
        refs = evidence_ids(row["Evidence"])
        if status == "ALIGNED" and not refs:
            fail(f"Documentation alignment row {index} ALIGNED requires evidence")
        unknown_refs = refs - evidence_index.keys()
        if unknown_refs:
            fail(
                "Documentation alignment row "
                f"{index} references unknown evidence: {sorted(unknown_refs)}"
            )
        if status == "ALIGNED":
            require_pass_evidence(
                refs,
                f"Documentation alignment row {index}",
            )
        if status in {"CONFLICT", "UNVERIFIED"} and not row["Action"].strip():
            fail(f"Documentation alignment row {index} requires an action")
        unresolved_documentation = (
            unresolved_documentation
            or status in {"CONFLICT", "UNVERIFIED"}
        )

    if (
        metadata["Receipt"] == "READY"
        and unresolved_documentation
        and metadata["Work status"] != "BLOCKED"
    ):
        fail(
            "READY receipt with unresolved documentation must have "
            "Work status BLOCKED"
        )

    if metadata["Work status"] == "COMPLETE" and unresolved_documentation:
        fail("COMPLETE work cannot have unresolved documentation")
    if (
        metadata["Work status"] == "COMPLETE"
        and metadata["Receipt"] != "READY"
    ):
        fail("COMPLETE work requires a READY receipt")

    require_development_work(metadata["First action"], "First action")

    state_refs = evidence_ids("\n".join(model["sections"]["State verification"]))
    unknown_state_refs = state_refs - evidence_index.keys()
    if unknown_state_refs:
        fail(
            "State verification references unknown evidence: "
            + ", ".join(sorted(unknown_state_refs))
        )
    if metadata["Receipt"] == "READY":
        if not state_refs:
            fail("READY receipt requires evidence in State verification")
        require_pass_evidence(state_refs, "State verification")

    prompt = model["prompt"]
    prompt_lines = [line.strip() for line in prompt.splitlines() if line.strip()] if prompt else []
    current_prompt = bool(prompt_lines and prompt_lines[0] == CURRENT_PROMPT_COMMAND)
    continuation = model["continuation"]
    checklist = model["checklist"]
    work_summary = model["work_summary"]
    if metadata["Format"] in {"handoff-v4", "handoff-v5", "handoff-v6", "handoff-v7", "handoff-v8"} and continuation is not None:
        fail("handoff-v4, handoff-v5, and handoff-v6 receipts must not contain a Continuation decision")
    if metadata["Format"] in {"handoff-v5", "handoff-v6", "handoff-v7", "handoff-v8"} and work_summary is None:
        fail(f"{metadata['Format']} receipt requires a 작업 결과 요약")
    if current_prompt and continuation is None:
        fail("$handoff start prompt requires a Continuation decision")
    if continuation is not None:
        if continuation["Mode"] not in CONTINUATION_MODES:
            fail("Continuation decision.Mode has an unsupported value")
        if continuation["Branch or worktree"] != metadata["Branch or worktree"]:
            fail("Continuation decision.Branch or worktree must match metadata")
        if continuation["Mode"] == "PAUSE" and metadata["Work status"] == "COMPLETE":
            fail("PAUSE continuation cannot have COMPLETE work")
    if metadata["Format"] == "handoff-v3" and checklist is None:
        fail("handoff-v3 receipt requires a Handoff completion checklist")
    if metadata["Format"] == "handoff-v4" and checklist is None:
        fail("handoff-v4 receipt requires a Handoff completion checklist")
    if metadata["Format"] == "handoff-v5" and checklist is None:
        fail("handoff-v5 receipt requires a Handoff completion checklist")
    if metadata["Format"] in {"handoff-v6", "handoff-v7", "handoff-v8"} and checklist is None:
        fail("handoff-v6/v7 receipt requires a Handoff completion checklist")
    if current_prompt and checklist is None:
        fail("$handoff start prompt requires a Handoff completion checklist")
    if checklist is not None:
        expected_checklist = (
            COMPLETE_CHECKLIST_FIELDS
            if metadata["Work status"] == "COMPLETE"
            else UNFINISHED_CHECKLIST_FIELDS
        )
        if set(checklist) != set(expected_checklist):
            fail(
                "Handoff completion checklist items must be exactly: "
                + ", ".join(expected_checklist)
            )
        for item in expected_checklist:
            row = checklist[item]
            if row["Status"] != "PASS":
                fail(f"Handoff completion checklist.{item} must be PASS")
            refs = evidence_ids(row["Evidence"])
            if not refs:
                fail(f"Handoff completion checklist.{item} requires evidence")
            unknown_refs = refs - evidence_index.keys()
            if unknown_refs:
                fail(
                    "Handoff completion checklist."
                    f"{item} references unknown evidence: {sorted(unknown_refs)}"
                )
            require_pass_evidence(refs, f"Handoff completion checklist.{item}")
        state_lines = [line.strip() for line in model["sections"]["State verification"]]
        if f"- Branch or worktree: {metadata['Branch or worktree']}" not in state_lines:
            fail("Handoff completion checklist requires matching Branch or worktree state")
        if f"- HEAD: {metadata['Baseline commit']}" not in state_lines:
            fail("Handoff completion checklist requires matching HEAD state")
        if not any(line.startswith("- Working tree:") for line in state_lines):
            fail("Handoff completion checklist requires Working tree state")

    remaining_mapped_criteria: set[str] = set()
    for stage in stages:
        stage_id = stage["id"]
        require_development_work(stage["name"], f"{stage_id} name")
        for field in ("Outcome", "Verification", "First action"):
            require_development_work(stage["metadata"][field], f"{stage_id}.{field}")
        mapped = {
            item.strip()
            for item in stage["metadata"]["Maps to"].split(",")
            if item.strip()
        }
        if not mapped:
            fail(f"{stage_id}.Maps to must contain at least one criterion ID")
        unknown = mapped - criterion_index.keys()
        if unknown:
            fail(f"{stage_id} maps to unknown criteria: {sorted(unknown)}")
        if stage["metadata"]["State"] != "PASS":
            remaining_mapped_criteria.update(mapped)

        rows = stage["table"]["rows"]
        names = [row["Gate or criterion"] for row in rows]
        duplicates = sorted({name for name in names if names.count(name) > 1})
        if duplicates:
            fail(f"{stage_id} has duplicate gates or criteria: {duplicates}")
        common = {name for name in names if name in COMMON_GATES}
        if common != COMMON_GATES:
            missing = COMMON_GATES - common
            extra_duplicates = {
                name for name in COMMON_GATES if names.count(name) != 1
            }
            details = sorted(missing | extra_duplicates)
            fail(f"{stage_id} common gates are invalid: {details}")
        specific = [name for name in names if name not in COMMON_GATES]
        if not 1 <= len(specific) <= 3:
            fail(f"{stage_id} must contain one to three stage-specific criteria")
        for name in specific:
            if not name.startswith(f"{stage_id}-"):
                fail(f"{stage_id} specific criterion must start with {stage_id}-")
        for row in rows:
            status = row["Status"]
            if status not in CRITERION_STATUSES:
                fail(f"{stage_id}.{row['Gate or criterion']} has invalid status")
            refs = evidence_ids(row["Evidence"])
            if status == "PASS" and not refs:
                fail(
                    f"{stage_id}.{row['Gate or criterion']} PASS requires evidence"
                )
            unknown_refs = refs - evidence_index.keys()
            if unknown_refs:
                fail(
                    f"{stage_id}.{row['Gate or criterion']} references unknown "
                    f"evidence: {sorted(unknown_refs)}"
                )
            if status == "PASS":
                require_pass_evidence(
                    refs,
                    f"{stage_id}.{row['Gate or criterion']}",
                )
        if stage["metadata"]["State"] == "PASS" and any(
            row["Status"] != "PASS" for row in rows
        ):
            fail(f"{stage_id} cannot be PASS with an unmet gate")

    unfinished_required = {
        item_id
        for item_id, row in criterion_index.items()
        if row["Required"].lower() == "yes" and row["Status"] != "PASS"
    }
    missing_mappings = unfinished_required - remaining_mapped_criteria
    if missing_mappings:
        fail(
            "unfinished required criteria are not mapped to a stage: "
            + ", ".join(sorted(missing_mappings))
        )

    if metadata["Work status"] == "COMPLETE":
        incomplete = {
            item_id
            for item_id, row in criterion_index.items()
            if row["Required"].lower() == "yes" and row["Status"] != "PASS"
        }
        if incomplete:
            fail("COMPLETE work has unmet required criteria")
        if stages:
            fail("COMPLETE work must have no remaining stages")
    elif not stages:
        fail("ACTIVE or BLOCKED work must have at least one remaining stage")

    prompt = model["prompt"]
    routing = model["routing"]
    if metadata["Work status"] == "COMPLETE":
        if routing is not None:
            fail("COMPLETE work must not contain next-stage routing")
        if prompt is not None:
            fail("COMPLETE work must not contain a resume prompt")
        return
    if metadata["Format"] not in {"handoff-v4", "handoff-v5", "handoff-v6", "handoff-v7", "handoff-v8"} and prompt is None:
        fail("ACTIVE or BLOCKED work requires a resume prompt")
    if metadata["Format"] in {"handoff-v4", "handoff-v5", "handoff-v6", "handoff-v7", "handoff-v8"} and routing is None:
        fail("handoff-v4, handoff-v5, or handoff-v6 ACTIVE or BLOCKED work requires next-stage routing")
    if routing is not None:
        for key, value in routing.items():
            require_development_work(value, f"Next-stage routing.{key}")
        combination = (
            routing["Recommended model"],
            routing["Recommended reasoning"],
        )
        if (
            metadata["Format"] not in {"handoff-v6", "handoff-v7", "handoff-v8"}
            and combination in LEGACY_BELOW_MINIMUM_COMBINATIONS
        ):
            fail(
                "legacy below-Medium routing requires in-place migration "
                "before RESUME"
            )
        routing_combinations = (
            V7_ROUTING_COMBINATIONS
            if metadata["Format"] in {"handoff-v7", "handoff-v8"}
            else V6_ROUTING_COMBINATIONS
            if metadata["Format"] == "handoff-v6"
            else LEGACY_ROUTING_COMBINATIONS
        )
        if combination not in routing_combinations:
            fail("next-stage routing has an unsupported model/reasoning combination")
        if metadata["Format"] == "handoff-v6":
            availability = routing["Route availability"]
            fallback = (
                routing["Fallback model"],
                routing["Fallback reasoning"],
            )
            if combination == ("Astra", "Medium"):
                if availability != "inactive" or fallback != ("Sol", "High"):
                    fail("Astra Medium must be inactive with Sol High fallback")
            elif combination == ("Astra", "High"):
                if availability != "inactive" or fallback != ("Sol", "Extra High"):
                    fail("Astra High must be inactive with Sol Extra High fallback")
            elif availability != "active" or fallback != (
                "not-applicable",
                "not-applicable",
            ):
                fail("active non-Astra routes must use not-applicable fallbacks")
        if routing["Use Ultra"] not in {"yes", "no"}:
            fail("Next-stage routing.Use Ultra must be yes or no")
        ultra_evidence_values: list[str] = []
        for line in model["sections"]["Required context"]:
            match = re.fullmatch(r"-\s+Ultra evidence:\s*(.+)", line.strip())
            if match:
                ultra_evidence_values.append(match.group(1).strip())
        if routing["Use Ultra"] == "yes":
            if len(ultra_evidence_values) != 1:
                fail("Use Ultra yes requires exactly one Ultra evidence line")
            ultra_refs = evidence_ids(ultra_evidence_values[0])
            if not ultra_refs:
                fail("Ultra evidence must reference PASS evidence")
            unknown_ultra_refs = ultra_refs - evidence_index.keys()
            if unknown_ultra_refs:
                fail(f"Ultra evidence references unknown evidence: {sorted(unknown_ultra_refs)}")
            require_pass_evidence(ultra_refs, "Ultra evidence")
            if not any(
                evidence_index[item_id]["Summary"].startswith("Ultra independence:")
                for item_id in ultra_refs
            ):
                fail("Ultra evidence requires an 'Ultra independence:' PASS summary")
        elif ultra_evidence_values:
            fail("Ultra evidence must be omitted when Use Ultra is no")
        selected_stage = next(
            (
                stage
                for stage in stages
                if routing["Current stage"] == f"{stage['id']} — {stage['name']}"
            ),
            None,
        )
        if selected_stage is None or selected_stage["metadata"]["State"] == "PASS":
            fail("Next-stage routing.Current stage must name a non-PASS stage")
        expected_stage = next(
            (
                stage
                for stage in stages
                if stage["metadata"]["State"] in {"ACTIVE", "BLOCKED"}
            ),
            None,
        )
        if expected_stage is None:
            expected_stage = next(
                stage for stage in stages if stage["metadata"]["State"] != "PASS"
            )
        if selected_stage is not expected_stage:
            fail("Next-stage routing.Current stage must name the current unfinished stage")
        if metadata["First action"] != selected_stage["metadata"]["First action"]:
            fail("top-level First action must equal the selected stage First action")
        if routing["Goal"] != selected_stage["metadata"]["Outcome"]:
            fail("Next-stage routing.Goal must equal the selected stage Outcome")
        if routing["Change scope"] != selected_stage["metadata"]["Scope"]:
            fail("Next-stage routing.Change scope must equal the selected stage Scope")
        placeholder_values = {"-", "n/a", "none", "not applicable", "tbd"}
        for key in ("Completion condition", "Next checkpoint"):
            if routing[key].strip().casefold() in placeholder_values:
                fail(f"Next-stage routing.{key} must be observable")
        escalation = routing["Escalate when" if metadata["Format"] in {"handoff-v7", "handoff-v8"} else "Escalate to Sol High when"].strip()
        if escalation.casefold() in placeholder_values:
            fail("Next-stage routing escalation condition must be observable")
        if combination == ("Sol", "Extra High"):
            if not escalation.startswith(TOP_ROUTE_ESCALATION_PREFIX):
                fail("Sol Extra High routing must record highest-route evidence")
            top_route_evidence = escalation[len(TOP_ROUTE_ESCALATION_PREFIX) :].strip()
            if (
                not top_route_evidence
                or top_route_evidence.casefold() in placeholder_values
            ):
                fail("Sol Extra High routing must record highest-route evidence")
            top_route_refs = evidence_ids(top_route_evidence)
            if not top_route_refs:
                fail("Sol Extra High routing must reference PASS evidence")
            unknown_top_route_refs = top_route_refs - evidence_index.keys()
            if unknown_top_route_refs:
                fail(
                    "Sol Extra High routing references unknown evidence: "
                    f"{sorted(unknown_top_route_refs)}"
                )
            require_pass_evidence(top_route_refs, "Sol Extra High routing")
            if not any(
                evidence_index[item_id]["Summary"].startswith(
                    TOP_ROUTE_EVIDENCE_PREFIX
                )
                for item_id in top_route_refs
            ):
                fail(
                    "Sol Extra High routing requires a 'Top-route evidence:' "
                    "PASS summary"
                )
    if metadata["Format"] in {"handoff-v4", "handoff-v5", "handoff-v6", "handoff-v7", "handoff-v8"}:
        return

    prompt_lines = [line.strip() for line in prompt.splitlines() if line.strip()]
    if not prompt_lines or prompt_lines[0] not in {CURRENT_PROMPT_COMMAND, "$handoff"}:
        fail("New-session prompt must begin with $handoff start")
    if prompt.count("$handoff") != 1:
        fail("New-session prompt must invoke $handoff exactly once")

    common_control_lines = {
        f"Project scope: {metadata['Project scope']}",
        "Receipt: "
        + (
            "docs/HANDOFF.md"
            if metadata["Project scope"] == "."
            else f"{metadata['Project scope']}/docs/HANDOFF.md"
        ),
        f"Expected baseline: {metadata['Baseline commit']}",
        f"First action: {metadata['First action']}",
        "Begin actual work.",
        "Do not create a new handoff, report, or prompt.",
    }
    missing_control_lines = common_control_lines - set(prompt_lines)
    if missing_control_lines:
        fail(
            "New-session prompt is missing control lines: "
            + ", ".join(sorted(missing_control_lines))
        )

    if prompt_lines[0] == CURRENT_PROMPT_COMMAND:
        if routing is None:
            fail("$handoff start prompt requires next-stage routing")
        required_current_lines = {
            CURRENT_PROMPT_COMMAND,
            f"Branch or worktree: {metadata['Branch or worktree']}",
        }
        for key in PROMPT_STAGE_FIELDS:
            required_current_lines.add(f"{key}: {routing[key]}")
        missing_current_lines = required_current_lines - set(prompt_lines)
        if missing_current_lines:
            fail(
                "$handoff start prompt is missing control lines: "
                + ", ".join(sorted(missing_current_lines))
            )
        selected_routes = [
            line for line in prompt_lines if line.startswith("Selected route:")
        ]
        if selected_routes != [f"Selected route: {continuation['Mode']}"]:
            fail("$handoff start prompt selected route must match Continuation decision")
        disallowed_setup_lines = [
            line
            for line in prompt_lines
            if any(line.startswith(f"{key}:") for key in PROMPT_SETUP_FIELDS)
            or line.startswith("Routing is advisory:")
            or line.startswith("Handoff action:")
        ]
        if disallowed_setup_lines:
            fail("$handoff start prompt must not contain session setup recommendations")
        return

    legacy_required_control_lines = common_control_lines | {"Handoff action: RESUME"}
    missing_legacy_control_lines = legacy_required_control_lines - set(prompt_lines)
    if missing_legacy_control_lines:
        fail(
            "New-session prompt is missing control lines: "
            + ", ".join(sorted(missing_legacy_control_lines))
        )
    action_lines = [
        line for line in prompt_lines if line.startswith("Handoff action:")
    ]
    if action_lines != ["Handoff action: RESUME"]:
        fail("New-session prompt must contain exactly one RESUME action")
    routing_prompt_lines = {
        key: [line for line in prompt_lines if line.startswith(f"{key}:")]
        for key in ROUTING_FIELDS
    }
    advisory_lines = [
        line for line in prompt_lines if line.startswith("Routing is advisory:")
    ]
    if routing is not None:
        for key, value in routing.items():
            expected = f"{key}: {value}"
            if routing_prompt_lines[key] != [expected]:
                fail(
                    "New-session prompt routing does not match Required context: "
                    + key
                )
        if advisory_lines != [ROUTING_ADVISORY]:
            fail("New-session prompt must contain the exact routing advisory")

def extract_prompt(lines: list[str], work_status: str, format_name: str) -> str | None:
    nonblank = [line.strip() for line in lines if line.strip()]
    if format_name in {"handoff-v4", "handoff-v5", "handoff-v6", "handoff-v7", "handoff-v8"}:
        if nonblank != [NO_COPYABLE_PROMPT]:
            fail("handoff-v4, handoff-v5, and handoff-v6 must use exactly the no-copyable-prompt marker")
        return None
    if work_status == "COMPLETE":
        if nonblank != ["No new-session prompt: work is complete."]:
            fail(
                "COMPLETE work must use exactly "
                "'No new-session prompt: work is complete.'"
            )
        return None

    fence_indexes = [
        index
        for index, line in enumerate(lines)
        if line.strip().startswith("```")
    ]
    if len(fence_indexes) != 2:
        fail("New-session prompt must contain exactly one closed fenced block")
    start, end = fence_indexes
    if any(line.strip() for line in lines[:start] + lines[end + 1 :]):
        fail("New-session prompt must contain only its fenced block")
    collected = lines[start + 1 : end]
    return nonempty("\n".join(collected), "New-session prompt")


def parse_handoff(text: str) -> dict[str, Any]:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = normalized.split("\n")
    if not lines or lines[0].strip() != "# HANDOFF":
        fail("document must begin with # HANDOFF")
    metadata_lines, sections = split_sections(lines[1:])
    metadata = parse_metadata(metadata_lines)
    parallel = None
    if metadata["Format"] == "handoff-v8" or "### Parallel execution" in normalized:
        import importlib.util
        location = Path(__file__).with_name("parallel_contract.py")
        contract_spec = importlib.util.spec_from_file_location("_handoff_parallel", location)
        contract = importlib.util.module_from_spec(contract_spec)
        contract_spec.loader.exec_module(contract)
        try:
            parallel = contract.extract(normalized)
            if metadata["Format"] != "handoff-v8" or parallel is None:
                fail("parallel execution requires handoff-v8 and exactly one state block")
            state_text = "\n".join(sections["State verification"])
            if contract.extract(state_text) != parallel:
                fail("parallel state must be inside State verification")
            sections["State verification"] = contract.without_block(state_text).split("\n")
            if metadata["Receipt"] == "READY" and parallel["phase"] in {"ACTIVE", "STOPPING"}:
                fail("live parallel execution cannot be a READY receipt")
            if metadata["Work status"] == "COMPLETE" and parallel["phase"] != "COMPLETE":
                fail("complete receipt has unfinished parallel execution")
        except (contract.ParallelError, ValueError, TypeError, KeyError) as exc:
            fail(f"invalid parallel state: {exc}")
    tables = {
        name: parse_table(sections[name], name)
        for name in TABLE_SCHEMAS
    }
    stages = parse_stages(sections["Execution plan"])
    model = {
        "metadata": metadata,
        "sections": sections,
        "tables": tables,
        "stages": stages,
        "routing": parse_routing(
            sections["Required context"],
            metadata["Format"],
        ),
        "continuation": parse_continuation(sections["Required context"]),
        "checklist": parse_completion_checklist(sections["State verification"]),
        "work_summary": parse_work_summary(sections["Resume instructions"]),
        "prompt": extract_prompt(
            sections["New-session prompt"],
            metadata["Work status"],
            metadata["Format"],
        ),
    }
    model["parallel"] = parallel
    validate_model(model)
    if parallel is not None and parallel["phase"] != "COMPLETE":
        route = model["routing"]
        if not route or route["Current stage"].split(" ", 1)[0] != parallel["plan"]["stage_id"] or route["Goal"] != parallel["plan"]["goal"] or route["Use Ultra"] != "yes":
            fail("parallel plan must match the selected independent stage")
    return model


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def status_class(value: str) -> str:
    if value in {"READY", "COMPLETE", "PASS", "ALIGNED"}:
        return "good"
    if value in {"INVALID", "FAIL", "CONFLICT"}:
        return "bad"
    if value in {"STALE", "BLOCKED", "UNVERIFIED"}:
        return "warn"
    return "neutral"


def render_inline(value: str) -> str:
    output: list[str] = []
    cursor = 0
    for match in re.finditer(r"`([^`\n]+)`", value):
        output.append(esc(value[cursor : match.start()]))
        output.append("<code>" + esc(match.group(1)) + "</code>")
        cursor = match.end()
    output.append(esc(value[cursor:]))
    return "".join(output)


def render_simple_markdown(lines: list[str]) -> str:
    output: list[str] = []
    paragraph: list[str] = []
    list_kind: str | None = None
    in_code = False
    code_lines: list[str] = []

    def flush_paragraph() -> None:
        if paragraph:
            output.append("<p>" + render_inline(" ".join(paragraph)) + "</p>")
            paragraph.clear()

    def close_list() -> None:
        nonlocal list_kind
        if list_kind is not None:
            output.append(f"</{list_kind}>")
            list_kind = None

    for raw_line in lines:
        line = raw_line.rstrip()
        stripped = line.strip()
        if stripped.startswith("```"):
            flush_paragraph()
            close_list()
            if in_code:
                output.append("<pre><code>" + esc("\n".join(code_lines)) + "</code></pre>")
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        if not stripped:
            flush_paragraph()
            close_list()
            continue
        if stripped.startswith("|"):
            continue
        if stripped.startswith("### "):
            flush_paragraph()
            close_list()
            output.append("<h3>" + render_inline(stripped[4:]) + "</h3>")
            continue
        unordered = re.match(r"^[-*]\s+(.*)$", stripped)
        ordered = re.match(r"^[0-9]+\.\s+(.*)$", stripped)
        if unordered or ordered:
            flush_paragraph()
            desired = "ul" if unordered else "ol"
            if list_kind != desired:
                close_list()
                output.append(f"<{desired}>")
                list_kind = desired
            item = unordered.group(1) if unordered else ordered.group(1)
            output.append("<li>" + render_inline(item) + "</li>")
            continue
        close_list()
        paragraph.append(stripped)
    if in_code:
        fail("unclosed fenced code block")
    flush_paragraph()
    close_list()
    return "".join(output)


def render_table(table: dict[str, Any], *, first_column_header: bool = False) -> str:
    headers = table["headers"]
    head = "".join(f"<th scope=col>{esc(value)}</th>" for value in headers)
    rows: list[str] = []
    for row in table["rows"]:
        cells: list[str] = []
        for index, header in enumerate(headers):
            value = row[header]
            tag = "th scope=row" if first_column_header and index == 0 else "td"
            css = status_class(value)
            cells.append(f"<{tag} class={css}>{render_inline(value)}</{tag.split()[0]}>")
        rows.append("<tr>" + "".join(cells) + "</tr>")
    return "<div class=table-wrap><table><thead><tr>" + head + "</tr></thead><tbody>" + "".join(rows) + "</tbody></table></div>"


def load_font_data() -> str:
    font_path = Path(__file__).resolve().parents[1] / "assets" / "PretendardVariable.woff2"
    if not font_path.is_file() or is_link_path(font_path):
        fail(f"bundled font is missing or unsafe: {font_path}")
    raw = font_path.read_bytes()
    if len(raw) > 3_000_000:
        fail("bundled font is unexpectedly large")
    return base64.b64encode(raw).decode("ascii")


def render_html(model: dict[str, Any], source_sha256: str) -> str:
    metadata = model["metadata"]
    tables = model["tables"]
    sections = model["sections"]
    stages = model["stages"]
    routing = model["routing"]
    criteria = tables["Global success criteria"]["rows"]
    required_rows = [row for row in criteria if row["Required"].lower() == "yes"]
    required_pass = sum(row["Status"] == "PASS" for row in required_rows)
    required_total = len(required_rows)
    progress = round(required_pass * 100 / required_total) if required_total else 100
    work_status_label = {
        "ACTIVE": "진행 중",
        "BLOCKED": "멈춤 — 확인 또는 결정 필요",
        "COMPLETE": "완료",
    }[metadata["Work status"]]

    def stage_label(stage: dict[str, Any]) -> str:
        return f"{stage['id']} — {stage['name']}"

    current_stage = None
    if routing is not None:
        current_stage = next(
            stage
            for stage in stages
            if stage_label(stage) == routing["Current stage"]
        )
    if current_stage is None:
        current_stage = next(
            (
                stage
                for stage in stages
                if stage["metadata"]["State"] in {"ACTIVE", "BLOCKED"}
            ),
            None,
        )
    if current_stage is None:
        current_stage = next(
            (stage for stage in stages if stage["metadata"]["State"] != "PASS"),
            None,
        )

    def strategic_goal() -> str:
        preferred = ("Objective:", "Goal:", "목표:")
        candidates: list[str] = []
        for raw_line in sections["Strategic alignment"]:
            line = re.sub(r"^[-*]\s+", "", raw_line.strip())
            if not line or line.startswith(("|", "```", "### ")):
                continue
            candidates.append(line)
            for prefix in preferred:
                if line.casefold().startswith(prefix.casefold()):
                    return nonempty(line[len(prefix) :], "Strategic alignment goal")
        if not candidates:
            return "Verified work transfer"
        first = candidates[0]
        sentence = re.match(r"^(.{1,220}?[.!?])(?:\s|$)", first)
        if sentence is not None:
            return sentence.group(1)
        if len(first) > 220:
            return first[:217].rstrip() + "…"

        return first
    goal = routing["Goal"] if routing is not None else strategic_goal()
    current_label = stage_label(current_stage) if current_stage else "완료"
    completion = (
        routing["Completion condition"]
        if routing is not None
        else (
            current_stage["metadata"]["Verification"]
            if current_stage
            else "모든 required 성공 기준이 PASS입니다."
        )
    )
    change_scope = (
        routing["Change scope"]
        if routing is not None
        else (current_stage["metadata"]["Scope"] if current_stage else "변경 없음")
    )
    next_checkpoint = (
        routing["Next checkpoint"]
        if routing is not None
        else "기존 v2 영수증에 별도 확인 시점이 기록되지 않았습니다."
    )

    unresolved_required = [row for row in required_rows if row["Status"] != "PASS"]
    unresolved_docs = [
        row
        for row in tables["Documentation alignment"]["rows"]
        if row["Alignment"] in {"CONFLICT", "UNVERIFIED"}
    ]
    attention_rows: list[str] = []
    for row in unresolved_required:
        attention_rows.append(
            f"<li><span class='status-token {status_class(row['Status'])}'>{esc(row['ID'])} · {esc(row['Status'])}</span>"
            f"<div><strong>{esc(row['Criterion'])}</strong><small>{esc(row['Evidence'])}</small></div></li>"
        )
    for row in unresolved_docs:
        attention_rows.append(
            f"<li><span class='status-token {status_class(row['Alignment'])}'>문서 · {esc(row['Alignment'])}</span>"
            f"<div><strong>{esc(row['Topic or decision'])}</strong><small>{esc(row['Action'])}</small></div></li>"
        )
    if current_stage is not None:
        for row in current_stage["table"]["rows"]:
            if row["Gate or criterion"] == "next-input" and row["Status"] != "PASS":
                attention_rows.append(
                    f"<li><span class='status-token {status_class(row['Status'])}'>next-input · {esc(row['Status'])}</span>"
                    f"<div><strong>다음 입력 또는 결정이 아직 확인되지 않았습니다.</strong>"
                    f"<small>{esc(row['Evidence'])}</small></div></li>"
                )
    if metadata["Work status"] == "BLOCKED":
        attention_rows.insert(
            0,
            "<li><span class='status-token warn'>BLOCKED</span>"
            "<div><strong>작업이 차단된 상태입니다.</strong>"
            "<small>아래 위험 및 문서 정합성 기록에서 해제 조건을 확인하세요.</small></div></li>",
        )
    attention_report = (
        "<ul class=attention-list>" + "".join(attention_rows) + "</ul>"
        if attention_rows
        else "<p class=clear-state>현재 기록된 필수 blocker나 미확인 required 기준이 없습니다.</p>"
    )

    stage_rail = "".join(
        (
            f"<li class='{status_class(stage['metadata']['State'])}'"
            + (" aria-current=step" if stage is current_stage else "")
            + f"><span>{esc(stage['id'])}</span><div><strong>{esc(stage['name'])}</strong>"
            f"<small>{esc(stage['metadata']['State'])}</small></div></li>"
        )
        for stage in stages
    )

    def render_stage(stage: dict[str, Any]) -> str:
        is_current = stage is current_stage
        gate_rows = "".join(
            f"<li><span class='status-token {status_class(row['Status'])}'>{esc(row['Status'])}</span>"
            f"<div><strong>{esc(row['Gate or criterion'])}</strong><small>{esc(row['Evidence'])}</small></div></li>"
            for row in stage["table"]["rows"]
        )
        return f"""<details class='stage-detail{' current' if is_current else ''}'{' open' if is_current else ''}>
<summary><span><b>{esc(stage['id'])}</b>{esc(stage['name'])}</span><span class='badge {status_class(stage['metadata']['State'])}'>{esc(stage['metadata']['State'])}</span></summary>
<div class=stage-body><dl class=stage-meta><div><dt>이 단계의 목표</dt><dd>{esc(stage['metadata']['Outcome'])}</dd></div>
<div><dt>수정 범위</dt><dd>{esc(stage['metadata']['Scope'])}</dd></div>
<div><dt>확인 방법</dt><dd>{esc(stage['metadata']['Verification'])}</dd></div>
<div><dt>첫 행동</dt><dd>{esc(stage['metadata']['First action'])}</dd></div>
<div><dt>연결된 완료 기준</dt><dd>{esc(stage['metadata']['Maps to'])}</dd></div></dl>
<ul class=checklist>{gate_rows}</ul></div></details>"""

    if stages:
        execution_report = (
            f"<ol class=stage-rail aria-label='Execution stages'>{stage_rail}</ol>"
            + "".join(render_stage(stage) for stage in stages)
        )
    else:
        execution_report = "<p class=clear-state>No remaining stages.</p>"

    if routing is None:
        routing_report = """<div class=legacy-route><strong>Legacy handoff-v2 receipt</strong><p>모델 라우팅이 기록되지 않았습니다. RESUME에서 저장소 상태와 단계 복잡도를 다시 평가하세요.</p></div>"""
    else:
        availability = routing.get("Route availability", "active")
        fallback_model = routing.get("Fallback model", "not-applicable")
        fallback_reasoning = routing.get("Fallback reasoning", "not-applicable")
        fallback_report = ""
        if availability == "inactive":
            fallback_report = (
                "<div><span>현재 실행 대안</span><strong>"
                f"{esc(fallback_model)} + {esc(fallback_reasoning)}"
                "</strong></div>"
            )
        availability_report = (
            f"<div><span>가용 상태</span><strong>{esc(availability)}</strong></div>"
            if "Route availability" in routing else ""
        )
        escalation = routing.get("Escalate when", routing.get("Escalate to Sol High when", ""))
        routing_report = f"""<div class=route-grid>
<div><span>권장 모델</span><strong>{esc(routing['Recommended model'])}</strong></div>
<div><span>권장 reasoning</span><strong>{esc(routing['Recommended reasoning'])}</strong></div>
{availability_report}
{fallback_report}
<div><span>Ultra</span><strong>{esc(routing['Use Ultra'])}</strong></div>
</div>
<dl class=route-conditions><div><dt>상위 라우팅 전환 조건</dt><dd>{esc(escalation)}</dd></div>
<div><dt>다음 확인 시점</dt><dd>{esc(next_checkpoint)}</dd></div></dl>"""

    context_lines = sections["Required context"]
    routing_heading_index = next(
        (
            index
            for index, line in enumerate(context_lines)
            if line.strip() == ROUTING_HEADING
        ),
        None,
    )
    if routing_heading_index is not None:
        context_lines = context_lines[:routing_heading_index]

    def audit_detail(title: str, subtitle: str, body: str) -> str:
        return (
            f"<details class=audit-detail><summary><span>{esc(title)}</span>"
            f"<small>{esc(subtitle)}</small></summary><div class=audit-body>{body}</div></details>"
        )

    audit_report = "".join(
        [
            audit_detail("병렬 작업", "메인 검토와 통합 상태",
                "<div class=prose>" + (
                    "<p>" + esc(model["parallel"]["phase"]) + " · revision " + esc(model["parallel"]["revision"]) + "</p><ul>" +
                    "".join("<li>" + esc(t["id"]) + ": " + esc(model["parallel"]["tasks"][t["id"]]["status"]) +
                            " · " + esc(t["model"]) + " / " + esc(t["reasoning"]) + "</li>"
                            for t in model["parallel"]["plan"]["tasks"]) + "</ul>"
                    if model.get("parallel") else "<p>순차 작업</p>") + "</div>"),
            audit_detail("재개 순서", "상세 작업 절차", f"<div class=prose>{render_simple_markdown(sections['Resume instructions'])}</div>"),
            audit_detail("작업 목표와 주의사항", "목표와 guardrail 원문", f"<div class=prose>{render_simple_markdown(sections['Strategic alignment'])}</div>"),
            audit_detail("문서 정합성", f"{len(tables['Documentation alignment']['rows'])}개 판단", render_table(tables["Documentation alignment"])),
            audit_detail("전체 완료 기준", f"필수 {required_pass}/{required_total}개 통과", render_table(tables["Global success criteria"], first_column_header=True)),
            audit_detail("계획 변경 이력", "이전 계획과 수정 계획", render_table(tables["Plan review"])),
            audit_detail("확인 근거", f"{len(tables['Evidence']['rows'])}개 근거", render_table(tables["Evidence"], first_column_header=True)),
            audit_detail("저장소 상태", "브랜치 · HEAD · 작업 트리", f"<div class=prose>{render_simple_markdown(sections['State verification'])}</div>"),
            audit_detail("남은 위험과 질문", "해결 전 확인할 내용", f"<div class=prose>{render_simple_markdown(sections['Risks and open questions'])}</div>"),
            audit_detail("새 세션 참고 자료", "새 세션이 읽어야 할 자료", f"<div class=prose>{render_simple_markdown(context_lines)}</div>"),
        ]
    )

    prompt_report = (
        f"<pre><code>{esc(model['prompt'])}</code></pre>"
        if model["prompt"] is not None
        else "<p class=clear-state>Work is complete; no new-session prompt was generated.</p>"
    )
    if metadata["Work status"] == "COMPLETE":
        next_session_report = f"""<section class='section decision-brief complete-brief' id=resume-brief><div class=section-head><div><span class=eyebrow>한눈에 보기</span><h2>작업이 완료되었습니다</h2></div><p>다음 세션에서 이어서 할 작업은 없습니다.</p></div><div class=decision-grid><div class='decision-card primary'><span>현재 상태</span><strong>{esc(work_status_label)}</strong><p>필수 완료 기준 {required_pass}/{required_total}개가 모두 통과했습니다.</p></div></div></section>"""
        prompt_section = ""
    else:
        next_session_report = f"""<section class='section decision-brief' id=resume-brief><div class=section-head><div><span class=eyebrow>한눈에 보기</span><h2>다음에 할 일</h2></div><p>아래 네 가지만 확인하면 바로 이어서 작업할 수 있습니다.</p></div>
<div class=decision-grid><div class='decision-card primary'><span>지금 바로 할 일</span><strong>{esc(metadata['First action'])}</strong><p>현재 단계: {esc(current_label)}</p></div><div class=decision-card><span>현재 상태</span><strong>{esc(work_status_label)}</strong><p>필수 완료 기준 {required_pass}/{required_total}개 통과</p></div><div class=decision-card><span>작업 위치</span><strong>{esc(metadata['Branch or worktree'])}</strong><p>기준 커밋: {esc(metadata['Baseline commit'])}</p></div><div class=decision-card><span>이번 단계 완료 기준</span><p>{esc(completion)}</p></div><div class=decision-card><span>수정 범위와 다음 확인</span><p>{esc(change_scope)}</p><small>다음 확인: {esc(next_checkpoint)}</small></div></div></section>
<section class='section route-section'><div class=section-head><div><span class=eyebrow>새 세션 설정</span><h2>모델 추천</h2></div><p>선호 경로와 현재 실행 가능한 대안을 확인하세요.</p></div><span class=advisory>모델 추천은 복사 프롬프트와 별개입니다. 재개 시에는 저장소 상태와 모델 가용성을 다시 확인하세요.</span>{routing_report}</section>"""
        prompt_section = f"""<section class='section prompt-section' id=new-session-prompt><div class=section-head><div><span class=eyebrow>새 세션에 붙여 넣기</span><h2>재개 프롬프트</h2></div><p>위 모델 설정 후, 아래 내용을 새 task에 그대로 입력하세요.</p></div>{prompt_report}</section>"""

    font_data = load_font_data()
    marker = f"{MARKER_PREFIX} source-sha256={source_sha256} -->"
    return f"""{marker}
<!doctype html>
<html lang=ko>
<head>
<meta charset=utf-8>
<meta name=viewport content="width=device-width, initial-scale=1">
<meta http-equiv=Content-Security-Policy content="default-src 'none'; style-src 'unsafe-inline'; font-src data:; base-uri 'none'; form-action 'none'">
<title>Handoff · {esc(goal)}</title>
<style>
@font-face{{font-family:Pretendard;src:url(data:font/woff2;base64,{font_data}) format('woff2');font-weight:45 920;font-display:swap}}
:root{{--ink:#1e1e1e;--muted:#656565;--line:#d2d2d2;--paper:#fff;--canvas:#f5f5f5;--accent:#7823dc;--accent-soft:#f1e8fb;--green:#08783e;--green-soft:#e8f5ee;--amber:#8a5a00;--amber-soft:#fff3d6;--red:#b3261e;--red-soft:#fcebea}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;background:var(--canvas);color:var(--ink);font-family:Pretendard,"Segoe UI",sans-serif;line-height:1.55;word-break:keep-all}}a{{color:inherit}}.skip-link{{position:fixed;left:16px;top:-60px;z-index:10;background:var(--ink);color:#fff;padding:10px 14px}}.skip-link:focus{{top:12px}}
.page{{width:min(1120px,calc(100% - 40px));margin:32px auto;background:var(--paper);border:1px solid var(--line)}}.report-top{{padding:34px 40px 28px;border-bottom:1px solid var(--line)}}.top-row{{display:flex;justify-content:space-between;gap:24px;align-items:flex-start}}.eyebrow{{color:var(--accent);font-size:11px;font-weight:780;letter-spacing:.08em;text-transform:uppercase}}h1,h2,h3,p{{margin:0}}h1{{max-width:820px;margin-top:8px;font-size:30px;line-height:1.22;font-weight:650;letter-spacing:-.025em}}h2{{font-size:20px;line-height:1.3}}h3{{font-size:16px}}.badges{{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}}.badge,.status-token{{display:inline-flex;align-items:center;width:max-content;border:1px solid var(--line);padding:4px 8px;font-size:11px;font-weight:760;letter-spacing:.02em}}.good{{color:var(--green)}}.badge.good,.status-token.good{{background:var(--green-soft);border-color:#acd6be}}.warn{{color:var(--amber)}}.badge.warn,.status-token.warn{{background:var(--amber-soft);border-color:#dfc27a}}.bad{{color:var(--red)}}.badge.bad,.status-token.bad{{background:var(--red-soft);border-color:#e7aaa5}}.neutral{{color:var(--muted)}}
.meta-line{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin-top:28px;padding-top:18px;border-top:1px solid var(--line)}}.meta-line div{{min-width:0}}.meta-line span,.route-grid span{{display:block;color:var(--muted);font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.04em}}.meta-line strong{{display:block;margin-top:4px;font-size:13px;font-weight:560;overflow-wrap:anywhere}}
.section{{padding:30px 40px;border-bottom:1px solid var(--line)}}.section-head{{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:18px}}.section-head p{{color:var(--muted);font-size:13px}}.progress-copy{{display:flex;justify-content:space-between;gap:16px;align-items:baseline;margin-bottom:8px}}.progress-copy strong{{font-size:24px}}.progress-copy span{{color:var(--muted);font-size:13px}}.progress{{height:8px;background:#e6e6e6;overflow:hidden}}.progress span{{display:block;height:100%;background:var(--accent)}}
.decision-brief{{border-left:3px solid var(--accent);background:linear-gradient(100deg,var(--accent-soft),#fff 68%)}}.decision-grid{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:18px}}.decision-card{{min-width:0;padding:18px;border:1px solid var(--line);background:#fff}}.decision-card.primary{{grid-column:1/-1;border-color:#cba9ee;background:#fff}}.decision-card span{{display:block;color:var(--muted);font-size:11px;font-weight:760;letter-spacing:.04em}}.decision-card strong,.decision-card p{{display:block;margin-top:5px;font-size:15px;line-height:1.48;overflow-wrap:anywhere}}.decision-card.primary strong{{font-size:19px;letter-spacing:-.015em}}.decision-card small{{display:block;margin-top:7px;color:var(--muted);font-size:12px;overflow-wrap:anywhere}}
.route-section{{background:linear-gradient(90deg,var(--accent-soft),#fff 72%)}}.advisory{{display:inline-block;margin-bottom:16px;color:var(--accent);font-size:12px;font-weight:720}}.route-grid{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border-top:1px solid var(--line);border-left:1px solid var(--line)}}.route-grid div{{padding:16px 18px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}}.route-grid strong{{display:block;margin-top:5px;font-size:20px}}.route-conditions{{margin:14px 0 0}}.route-conditions div{{display:grid;grid-template-columns:170px 1fr;gap:18px;padding:10px 0;border-bottom:1px solid var(--line)}}dt{{color:var(--muted);font-size:12px;font-weight:700}}dd{{margin:0;overflow-wrap:anywhere}}.legacy-route{{border:1px solid var(--line);padding:17px 18px}}.legacy-route p{{margin-top:5px;color:var(--muted)}}
.attention-section{{background:#fffcf5}}.attention-list,.checklist{{list-style:none;margin:0;padding:0;border-top:1px solid var(--line)}}.attention-list li,.checklist li{{display:grid;grid-template-columns:max-content 1fr;gap:14px;padding:13px 0;border-bottom:1px solid var(--line);align-items:start}}.attention-list strong,.checklist strong{{display:block;font-size:13px}}.attention-list small,.checklist small{{display:block;margin-top:3px;color:var(--muted);font-size:12px;overflow-wrap:anywhere}}.clear-state{{color:var(--muted)}}
.stage-rail{{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));margin:0 0 18px;padding:0;list-style:none;border:1px solid var(--line)}}.stage-rail li{{position:relative;display:grid;grid-template-columns:30px 1fr;gap:9px;padding:14px;background:#fff;border-right:1px solid var(--line)}}.stage-rail li:last-child{{border-right:0}}.stage-rail li[aria-current=step]{{background:var(--accent-soft);border-bottom:3px solid var(--accent);padding-bottom:11px}}.stage-rail li>span{{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border:1px solid currentColor;border-radius:50%;font-size:11px;font-weight:780}}.stage-rail strong,.stage-rail small{{display:block}}.stage-rail strong{{font-size:12px}}.stage-rail small{{margin-top:2px;font-size:10px}}
.stage-detail,.audit-detail{{border:1px solid var(--line);border-bottom:0}}.stage-detail:last-child,.audit-detail:last-child{{border-bottom:1px solid var(--line)}}summary{{cursor:pointer;list-style:none}}summary::-webkit-details-marker{{display:none}}summary:focus-visible{{outline:3px solid #b98be9;outline-offset:2px}}.stage-detail>summary,.audit-detail>summary{{display:grid;grid-template-columns:minmax(0,1fr) auto 20px;gap:16px;align-items:center;padding:15px 17px}}.stage-detail>summary::after,.audit-detail>summary::after{{content:"+";color:var(--accent);font-size:18px;font-weight:650;text-align:center}}.stage-detail[open]>summary::after,.audit-detail[open]>summary::after{{content:"−"}}.stage-detail>summary span:first-child{{display:flex;gap:10px;align-items:center}}.stage-detail.current>summary{{background:var(--accent-soft)}}.stage-body,.audit-body{{padding:18px;border-top:1px solid var(--line)}}.stage-meta{{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));margin:0 0 18px;border-top:1px solid var(--line);border-left:1px solid var(--line)}}.stage-meta div{{padding:12px 14px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}}.stage-meta dd{{margin-top:4px;font-size:13px}}.audit-detail>summary small{{color:var(--muted)}}
.prose p{{margin:8px 0}}.prose ul,.prose ol{{margin:8px 0;padding-left:22px}}.prose li{{margin:4px 0}}code{{font-family:"Cascadia Mono",Consolas,monospace;overflow-wrap:anywhere}}pre{{margin:0;max-height:520px;overflow:auto;padding:17px;background:#1e1e1e;color:#fff;white-space:pre-wrap;word-break:break-word}}.table-wrap{{overflow:auto;border:1px solid var(--line)}}table{{width:100%;border-collapse:collapse;font-size:12px;word-break:normal}}th,td{{padding:10px 11px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top;overflow-wrap:anywhere}}thead th{{background:var(--canvas);color:var(--muted);font-size:10px;letter-spacing:.04em;text-transform:uppercase}}tbody tr:last-child th,tbody tr:last-child td{{border-bottom:0}}tbody th{{font-weight:650}}.prompt-section{{border-left:3px solid var(--accent)}}.footer{{padding:18px 40px;color:var(--muted);font-size:11px;overflow-wrap:anywhere}}
@media(max-width:760px){{.page{{width:100%;margin:0;border:0}}.report-top,.section{{padding-left:22px;padding-right:22px}}.top-row{{display:block}}.badges{{justify-content:flex-start;margin-top:16px}}.meta-line,.decision-grid,.route-grid,.stage-meta{{grid-template-columns:1fr}}.decision-card.primary{{grid-column:auto}}.route-conditions div{{grid-template-columns:1fr;gap:4px}}.stage-rail{{grid-template-columns:1fr}}.stage-rail li{{border-right:0;border-bottom:1px solid var(--line)}}.stage-rail li:last-child{{border-bottom:0}}.section-head{{display:block}}.section-head p{{margin-top:4px}}}}
@media print{{body{{background:#fff}}.page{{width:100%;margin:0;border:0}}details:not([open])>*:not(summary){{display:block!important}}.skip-link{{display:none}}}}
</style>
</head>
<body>
<a class=skip-link href=#resume-brief>핵심 요약으로 이동</a>
<main class=page>
<header class=report-top><div class=top-row><div><span class=eyebrow>Verified cross-session handoff</span><h1>{render_inline(goal)}</h1></div>
<div class=badges><span class='badge {status_class(metadata['Receipt'])}'>Receipt · {esc(metadata['Receipt'])}</span><span class='badge {status_class(metadata['Work status'])}'>Work · {esc(metadata['Work status'])}</span></div></div>
<div class=meta-line><div><span>Project scope</span><strong>{esc(metadata['Project scope'])}</strong></div><div><span>Branch or worktree</span><strong>{esc(metadata['Branch or worktree'])}</strong></div><div><span>Baseline</span><strong>{esc(metadata['Baseline commit'])}</strong></div><div><span>Last verified</span><strong>{esc(metadata['Last verified'])}</strong></div></div></header>
<section class=section aria-labelledby=progress-title><div class=progress-copy><div><span id=progress-title>필수 완료 기준</span><strong>{required_pass}/{required_total}개 통과</strong></div><span>{progress}%</span></div><div class=progress role=progressbar aria-label='필수 완료 기준 진행률' aria-valuemin=0 aria-valuemax={required_total} aria-valuenow={required_pass}><span style='width:{progress}%'></span></div></section>
{next_session_report}
<section class='section attention-section'><div class=section-head><div><span class=eyebrow>먼저 확인</span><h2>지금 확인할 것</h2></div><p>멈춘 이유, 미완료 기준, 문서 충돌만 표시합니다.</p></div>{attention_report}</section>
<section class=section><div class=section-head><div><span class=eyebrow>작업 상세</span><h2>단계와 확인 항목</h2></div><p>현재 단계만 기본으로 펼칩니다.</p></div>{execution_report}</section>
<section class=section><div class=section-head><div><span class=eyebrow>세부 근거</span><h2>근거와 원문</h2></div><p>판단이 필요할 때만 펼쳐 확인하세요.</p></div>{audit_report}</section>
{prompt_section}
<footer class=footer>Generated from docs/HANDOFF.md · source SHA-256 {esc(source_sha256)} · no JavaScript or external resources</footer>
</main>
</body>
</html>
"""

def output_snapshot(path: Path) -> tuple[bool, int, int, str]:
    if is_link_path(path):
        fail(f"output must not be a link or junction: {path}")
    if not path.exists():
        return (False, 0, 0, "")
    info = path.stat()
    if not stat.S_ISREG(info.st_mode):
        fail(f"output must be a regular file: {path}")
    if info.st_size > MAX_OUTPUT_BYTES:
        fail(f"existing generated HTML is unexpectedly large: {path}")
    raw = path.read_bytes()
    first_line = raw.splitlines()[0].decode("utf-8", errors="replace") if raw else ""
    if re.fullmatch(
        r"<!-- Generated by Handoff renderer; source-sha256=[0-9a-f]{64} -->",
        first_line,
    ) is None:
        fail(f"refusing to overwrite non-generated HTML: {path}")
    return (
        True,
        info.st_mtime_ns,
        info.st_size,
        hashlib.sha256(raw).hexdigest(),
    )


def directory_identity(path: Path) -> tuple[int, int]:
    info = path.stat()
    if not stat.S_ISDIR(info.st_mode):
        fail(f"output parent must be a directory: {path}")
    return (info.st_dev, info.st_ino)


def require_output_parent(
    root: Path,
    output: Path,
    expected_identity: tuple[int, int],
) -> None:
    reject_link_components(root, output)
    if directory_identity(output.parent) != expected_identity:
        fail(f"output parent changed during render: {output.parent}")


def acquire_lock(
    root: Path,
    output: Path,
    parent_identity: tuple[int, int],
) -> tuple[Path, str]:
    require_output_parent(root, output, parent_identity)
    lock_path = output.with_name(output.name + ".handoff-render.lock")
    token = uuid.uuid4().hex
    try:
        descriptor = os.open(
            lock_path,
            os.O_CREAT | os.O_EXCL | os.O_WRONLY,
            0o600,
        )
    except FileExistsError:
        fail(f"render lock exists: {lock_path}")
    with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(token + "\n")
        handle.flush()
        os.fsync(handle.fileno())
    return lock_path, token


def release_lock(
    root: Path,
    output: Path,
    parent_identity: tuple[int, int],
    lock_path: Path,
    token: str,
) -> None:
    require_output_parent(root, output, parent_identity)
    if not lock_path.exists() or is_link_path(lock_path):
        fail(f"render lock changed before cleanup: {lock_path}")
    content = lock_path.read_text(encoding="utf-8").strip()
    if content != token:
        fail(f"render lock ownership changed: {lock_path}")
    lock_path.unlink()


def write_atomic(
    root: Path,
    output: Path,
    content: str,
    original_snapshot: tuple[bool, int, int, str],
    parent_identity: tuple[int, int],
) -> None:
    require_output_parent(root, output, parent_identity)
    current_snapshot = output_snapshot(output)
    if current_snapshot != original_snapshot:
        fail(f"output changed during render: {output}")
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=".handoff-report-",
        suffix=".tmp",
        dir=output.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        require_output_parent(root, output, parent_identity)
        os.replace(temporary, output)
    finally:
        if temporary.exists():
            temporary.unlink()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", required=True)
    parser.add_argument("--handoff", default="docs/HANDOFF.md")
    parser.add_argument("--output", default="docs/HANDOFF.html")
    return parser.parse_args()


def main() -> int:
    lock_path: Path | None = None
    lock_token: str | None = None
    root: Path | None = None
    output: Path | None = None
    parent_identity: tuple[int, int] | None = None
    try:
        args = parse_args()
        lexical_root = Path(os.path.abspath(Path(args.project_root)))
        if is_link_path(lexical_root):
            fail(f"project root must not be a link or junction: {lexical_root}")
        root = lexical_root.resolve(strict=True)
        if not root.is_dir():
            fail(f"project root must be a real directory: {root}")
        source = resolve_inside(root, args.handoff, must_exist=True)
        output = resolve_inside(root, args.output, must_exist=False)
        if source == output:
            fail("handoff source and HTML output must differ")
        output.parent.mkdir(parents=True, exist_ok=True)
        reject_link_components(root, output)
        parent_identity = directory_identity(output.parent)

        source_raw = read_regular_utf8(source)
        source_sha256 = hashlib.sha256(source_raw).hexdigest()
        model = parse_handoff(source_raw.decode("utf-8"))
        require_output_parent(root, output, parent_identity)
        original_output = output_snapshot(output)
        lock_path, lock_token = acquire_lock(
            root,
            output,
            parent_identity,
        )
        rendered = render_html(model, source_sha256)
        if read_regular_utf8(source) != source_raw:
            fail(f"handoff changed during render: {source}")
        write_atomic(
            root,
            output,
            rendered,
            original_output,
            parent_identity,
        )
        release_lock(
            root,
            output,
            parent_identity,
            lock_path,
            lock_token,
        )
        lock_path = None
        lock_token = None
        print(str(output))
        return 0
    except (HandoffError, OSError) as exc:
        print(f"handoff report error: {exc}", file=sys.stderr)
        return 2
    finally:
        if (
            root is not None
            and output is not None
            and parent_identity is not None
            and lock_path is not None
            and lock_token is not None
        ):
            try:
                release_lock(
                    root,
                    output,
                    parent_identity,
                    lock_path,
                    lock_token,
                )
            except (HandoffError, OSError) as exc:
                print(f"handoff report cleanup error: {exc}", file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
